.gitignore, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> feat: Prdp 41 ci update helm chart

helm/values-uat.yaml
=> fix: UAT replica

README.md
- Improved README
- Added sonarcloud badge
[Issue PRDP-50](https://pagopa.atlassian.net/browse/PRDP-50?atlOrigin=eyJpIjoiYWE1NzRkMTAyZGQ5NDllMTg4YmMyMDhlMDM4ZjcwZmMiLCJwIjoiaiJ9)
[PRDP-50]: https://pagopa.atlassian.net/browse/PRDP-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PRDP-50] Update sonarcloud and refine logs

helm/values-dev.yaml
- Updated helm chart dev value in order to fix website name (removing '-' in name)
Aligning website name to other services
=> [PRDP-50] fix: updated helm charts dev values to fix websitename

helm/values-uat.yaml
- Updated helm chart values for uat enviroment with correct references to env. variables and key-vault secrets
Preparing the helm chart values for the initial uat deployment
=> [PRDP-48] ci: updated uat helm chart

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PdfEngineClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptBlobClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptQueueClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/Receipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/BizEventNotValidException.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/ReceiptNotFoundException.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/ObjectMapperUtils.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/ReceiptPdfUtils.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/TemplateMapperUtils.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/util/ObjectMapperUtilsTest.java
- Changed queue name in GenerateReceiptPdf from hardcoded to env variable
- Handled cases where both debtor's and payer's CF is null
- Changed Receipt entity partition key from idEvent to eventId
- Added more logs
- Cleaned and organized code
Issues raised during meeting and integration tests
Tested with both unit tests and local deploy
=> fix: Numerous fixes and code improvements

helm/values-uat.yaml
- Fixed receipt poison topic uat env
Wrong topic name for the poison queue in uat
=> [fix-uat-env] Fixed receipt poison topic uat env

src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueue.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessages.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
Ref to https://github.com/pagopa/pagopa-infra/pull/1123
- Updated logs to enable tracing on eventId in logs
Required to check for logs related to the appInsight in the receipt datastore process
=> [PRDP-58] feat: Updated logs for datastore processes

integration-test/src/config/.env.dev, integration-test/src/config/.env.local, integration-test/src/config/.env.uat, integration-test/src/features/receipt_pdf_datastore.feature, integration-test/src/step_definitions/biz_events_datastore_client.js, integration-test/src/step_definitions/common.js, integration-test/src/step_definitions/receipt_pdf_datastore_step.js, integration-test/src/step_definitions/receipts_blob_storage_client.js, integration-test/src/step_definitions/receipts_datastore_client.js, integration-test/src/step_definitions/reqeipt_queue_client.js
- Added specific test for poison queue to integration test
Run integration test pipeline
=> [PRDP-59] feat: Add poison queue test to integration test

.github/workflows/deploy_with_github_runner.yml
=> fix: Runner

Dockerfile, agent/config.yaml, helm/Chart.lock, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PdfEngineClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/request/PdfEngineRequest.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java
- Updated Chart version to 2.4.0
- Updated service and ingress configurations in helm values
- Introducing ServiceMonitor configuration
- Updated Dockerfile to include java-agent installation to export jmx metrics
- Updated stream management on templates
Changes required in the context of monitoring and performance
=> [PRDP-74] Export JMX Metrics to Prometheus

src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/PdfEngineClientImplTest.java
=> fixed PdfEngineClientImplTest

host.json
=> fix: host json

docker/run_docker.sh
- Updated run_docker.sh to properly check service info status code
=> [PRDP-93] fix run_docker.sh script

performance-test/src/test-types/constant.json
- Changed Constant scenario settings for performance tests
=> [prf-test-tuning] Changed Constant scenario settings

performance-test/README.md, performance-test/src/modules/datastore_client.js, src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessages.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdfTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueueTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessagesTest.java
-  configured k6 to not ignore response body
- change Logger for GenerateReceiptProcess function to Slf4j
- removed useless mock to fix unit tests
fix performance test
Run unit tests
Run performance test
=> [PRDP-107] fix: Configure k6 to not ignore response body

.github/workflows/code_review.yml, .github/workflows/integration_test.yml
Added github action to execute the integration tests choosing the environment
=> [PRDP-113] feat:Added integration-tests action

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: Aks limit

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: Mem req

.github/workflows/integration_test.yml
=> [fix] Fixed integration-test action notification

helm/Chart.yaml
Updated app name in Chart.yaml
=> [fix] Updated app name in Chart.yaml

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/Info.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java, src/main/resources/logback.xml, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
- added missing `slf4j-api`, `logback-ecs-encoder`, `janino ` dependency
- added missing environment variables in helm chart
- refactored log
- refactored BizEventToReceiptProcessor function to avoid nullpointer on log
Show log on console and application insight
=> fix: Show log on console, application insight and elastic

Dockerfile
=> fix: Fix dockerfile

src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
- Added filter for BizEvent with totalNotice > 1 (cart payments)
- Updated logger in service class
- Added unit tests to test filtering
[Issue PRDP-129](https://pagopa.atlassian.net/browse/PRDP-129?atlOrigin=eyJpIjoiZmFkYmVjOTFlNWFkNDk4MWI2YjAzZjM4NzRjNWE3ZGUiLCJwIjoiaiJ9)
Run unit tests with coverage
=> [PRDP-129] feat: Added total notice filter

src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Reverts pagopa/pagopa-receipt-pdf-datastore#60
=> Revert "[fix] Fixed totalNotice filter control on null value"

src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Fixed totalNotice filter control on null value
Datastore generation failed when totalNotice = null (unintended behavior)
Added unit test with total notice null
=> [fix] Fixed totalNotice filter control on null value

src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/Receipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
Added receipt's timestamps and timestamp "inserted_at" valorization 
[Issue PRDP-135](https://pagopa.atlassian.net/browse/PRDP-135?atlOrigin=eyJpIjoiMmVkZGM2Mzg3MDMzNDNkMmJkMjQ5NTkzY2QwYzQzZjgiLCJwIjoiaiJ9)
=> [PRDP-135] Added receipt's timestamps

performance-test/src/receipt_processor.js
Modified performance test following refactor
[Issue PRDP-124](https://pagopa.atlassian.net/browse/PRDP-124?atlOrigin=eyJpIjoiYWEyZDNmN2E0ZDA2NGQzODgxNjVlMjYwOTkyNGM3ZjciLCJwIjoiaiJ9)
=> [PRDP-124] Modified performance test following refactor

.devops/performance-test-pipelines.yml, performance-test/src/DockerfileReview, performance-test/src/DockerfileTeardown, performance-test/src/dev.environment.json, performance-test/src/local.environment.json, performance-test/src/modules/common.js, performance-test/src/modules/datastore_client.js, performance-test/src/package.json, performance-test/src/receipt_flow_simulation.js, performance-test/src/scripts/README.md, performance-test/src/scripts/review_script.js, performance-test/src/scripts/scripts_common.js, performance-test/src/scripts/teardown_script.js, performance-test/src/test-types/constant-prod.json, performance-test/src/uat.environment.json
- Added function to generate n. of bizEvent to be processed from datastore-generator-notifier
- Added function to retrieve receipts timestamp info and log metrics
- Added function to teardown and eliminate all the receipts, bizEvents and pdfs generated
[Issue PRDP-136](https://pagopa.atlassian.net/browse/PRDP-136?atlOrigin=eyJpIjoiY2ViNTc1ZWE2ZTdhNDdlYjk3YzUzYjJmNTY4NmEzNzMiLCJwIjoiaiJ9)
=> [PRDP-136] Added performance test to simulate prod load

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: deploy

helm/values-uat.yaml
Lowered max replica to "1" in uat environment
=> [feat] Lowered max replica to 1

src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/CartItem.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/EventData.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
- Introduced cart data for notification in receipt collection
- Updated unit tests regarding receipt insertion to datastore
=> [PRDP-104] feat: introducing cart data for notification in receipt

src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/DebtorPosition.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/PaymentInfo.java
Added IUR info to match biz event datastore's entity
Match the changes done to the BizEvent entity in [biz-event-datastore](https://github.com/pagopa/pagopa-biz-events-datastore)
=> [feat] Added IUR info to match biz event datastore's entity

src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
=> fix: Add amount to notify

src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/AuthRequest.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/BizEvent.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Creditor.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Debtor.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/DebtorPosition.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Details.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Info.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/MBD.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/MapEntry.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Payer.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/PaymentInfo.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Psp.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Transaction.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/TransactionDetails.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/TransactionPsp.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/User.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/WalletItem.java
- Added the property @JsonIgnoreProperties(ignoreUnknown = true) to every BizEvent's entity
Avoid having conflicts with new (and unused) properties added to the BizEvent object
=> [PRDP-155] feat: Added JsonIgnoreProperties ignoreUnknown to BizEvent's entities

.devops/performance-test-pipelines.yml, performance-test/src/scripts/teardown_script.js
- Fixed blob deletion in teardown script for performance test "simil-prod"
The script deleted the entire container and not the selected blob
=> [fix] Fixed blob deletion

.identity/00_data.tf, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: Prod-deploy

src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/Receipt.java
- Added section in receipt to store error that occur for payer elaboration
=> [PRDP-164] feat: Added specific section for payer error in receipt

.github/maven_code_review/action.yml, .github/workflows/code_review.yml, Dockerfile, host.json, pom.xml
- Migrated to java17
- Updated system-stubs-jupiter dependency
[Issue PRDP-193](https://pagopa.atlassian.net/browse/PRDP-193?atlOrigin=eyJpIjoiZTY5YjUwMWRmMGZlNDdlZjkwYzI2M2ZiM2U5ODlkMzkiLCJwIjoiaiJ9)
Run unit tests
=> [PRDP-193] Migrate to java17

README.md, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, performance-test/src/modules/common.js, performance-test/src/scripts/review_script.js, performance-test/src/scripts/teardown_script.js, src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/PDVTokenizerClient.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PDVTokenizerClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/PDVTokenizerException.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/ErrorResponse.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/InvalidParam.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/PiiResource.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/TokenResource.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/PDVTokenizerService.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PDVTokenizerClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptQueueClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImplTest.java
-  Defined PDV Tokenizer Client & Service
- Implemented PDV Tokenizer in BizEventToReceipt function
- Updated unit tests
[Issue PRDP-183](https://pagopa.atlassian.net/browse/PRDP-183?atlOrigin=eyJpIjoiNGE5ZjlhYTcxN2VmNGU2MGI0OTIwM2U0OWZhZGI5OGIiLCJwIjoiaiJ9)
The need is to save on CosmosDB tokenized fiscal codes
Run unit tests
=> [PRDP-183] Implement PDV Tokenizer for fiscal codes

.github/workflows/integration_test.yml
=> fix: Selfhost runner integtest

src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImpl.java
- Fixed response mapping for 404 status code for `/tokens/search` and `/tokens/{token}/pii` endpoint
=> fix: Tokenizer error response mapping

helm/values-prod.yaml
=> fix tokenier path

src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PDVTokenizerClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/enumeration/ReasonErrorCode.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
- Updated & allined reason error codes
- Cleaned code
=> [fix] Updated reason error codes

docker/run_docker.sh, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/Health.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/HealthTest.java
- added health function
Added dedicated endpoint for health check
=> feat: Add health function

.gitignore, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
=> fix: Payeename for notify

src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
=> fix payeename

performance-test/src/scripts/prod_test_script.js
=> Chore prod test script

performance-test/src/scripts/prod_test_script.js
- Improved prod test script to not save receipts already existing
Now the script doesn't generates receipts in status FAILED if already exists another receipt with the same biz event id
Tested in DEV
=> [chore] Improved prod test script to not save receipts already existing

integration-test/src/step_definitions/receipt_pdf_datastore_step.js, integration-test/src/step_definitions/receipts_datastore_client.js
- Fixed integration tests delete
The receipt partition key changed breaking the integration tests
=> [fix] Fixed integration tests delete

src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/User.java
- Added new biz event fields
Alline with ReceiptGenerator changes ([PR-98](https://github.com/pagopa/pagopa-receipt-pdf-generator/pull/98))
=> [feat] Added new fields name and surname to bizEvent User class

src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
- Updated to recover payer fiscal code from transactionDetails when bizEvent.payer data is missing
=> [PRDP-281] feat: add payer fiscal code from details

src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptCosmosClient.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
- added check to discard already processed biz-events
Discard already processed biz-events
=> [PRDP-282] feat: Add check to discard already processed biz-events

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java, src/test/resources/logback-test.xml
- added check to discard ecommerce events
=> [PRDP-301] feat: Discard ecommerce events

integration-test/src/step_definitions/common.js, performance-test/src/modules/common.js, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Transaction.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/enumeration/UserType.java
- updated `transactionId` and `idTransaction` type
- added values to `UserType` enum
- updated integration and performance tests
=> [PRDP-293] fix: Biz-event model

.github/workflows/code_review.yml, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, integration-test/src/step_definitions/common.js, performance-test/src/modules/common.js, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/CartReceiptsCosmosClient.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptCosmosClient.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/CartReceiptsCosmosClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/cart/CartForReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/cart/CartStatusType.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Transaction.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/enumeration/UserType.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/CartNotFoundException.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/CartReceiptsCosmosClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java, src/test/resources/logback-test.xml
depends on infra PR TBD @alessio-cialini
=> Prdp 72 feat add management for total notice

README.md, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
- added feature flag that enable/disable cart event processing
- fix binding name
=> [PRDP-308] feat: Add feature flag for cart processing

src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceiptTest.java
- Added check on cart status before processing
Avoid to process cart in wrong status
=> fix: Add cart status check

helm/values-prod.yaml
=> chore: Upd helm prod

integration-test/src/step_definitions/receipt_pdf_datastore_step.js
- Fixed typo in int test
[Issue PRDP-328](https://pagopa.atlassian.net/browse/PRDP-328?atlOrigin=eyJpIjoiNTUzYWYwM2EyM2I2NDRhZjk2ZTFkMDY1MWE0YTUxYjUiLCJwIjoiaiJ9)
=> [PRDP-328] fix: Fixed typo in int test

src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
- Added formatting to receipt amount
=> [PRDP-333] fix: Amount format

src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
- Improved fiscal code validation using a regex for [Codici Fiscali](https://it.wikipedia.org/wiki/Codice_fiscale) & [Partite IVA](https://it.wikipedia.org/wiki/Partita_IVA)
- Updated unit tests
[Issue PRDP-332](https://pagopa.atlassian.net/browse/PRDP-332?atlOrigin=eyJpIjoiNDNmNDc3Njk1ZTI2NDNhNTg5ZDE1MzkwNjg4N2EyNDQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
- fixed edge case for `debtor = null ` that was creating a receipt for a not valid user
- fixed edge case for payer and debtor with invalid fiscal codes different from "ANONIMO" (es. values such as "INVALID_FISCAL_CODE" were triggering a receipt generation)
=> [PRDP-332] Improved fiscal code validation and logic

src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
- updated check on discard event for invalid fiscal code by adding check on `transactionDetails.user.fiscalCode`
=> fix: Discard check on invalid fiscal code

src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
=> fix: Add origin check

src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
- Introduced remittance information check with regex against unwanted strings
[Issue PRDP-335](https://pagopa.atlassian.net/browse/PRDP-335?atlOrigin=eyJpIjoiNDlkYWI2YmNkMTU1NGRmYmE5MDc3MTYwNzBiY2NlMmQiLCJwIjoiaiJ9)
=> [PRDP-335] Introduced remittance information check with regex against unwanted strings

src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
- The remittanceInformation check against a regex is now case-insensitive
The regex was case-sensitive
=> [fix] Fix remittanceInformation regex

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/enumeration/BizEventStatusType.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
=> chore: Add log

src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
- checks for cart amount on minimal differences issue fixed
=> fix: bug on minimal difference for amounts

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> feat: Removed the eCommerce pdf generation filter

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, host.json, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
- log optimization
- cost containment
- junit test
=> feat: [PAGOPA-2299] opt log: update log conf

.github/workflows/integration_test.yml
- use self-hosted runner
Fix integration test execution
=> fix: Integration test gha runner

.github/maven_code_review/action.yml, .github/workflows/deploy_with_github_runner.yml, .github/workflows/release-deploy.yml, .identity/00_data.tf, .identity/03_github_environment.tf, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
- Implemented new runner
- Implemented workload identity with helm version 7.5.0
[PIDM-482](https://pagopa.atlassian.net/browse/PIDM-482)
[PIDM-482]: https://pagopa.atlassian.net/browse/PIDM-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [PIDM-482] Implement workload identity & new runner

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java, src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
- manage AUTH CHECKOUT channel
- missed payer receipt for events from authenticated CHECKOUT channel
- junit test
=> [PIDM-449] receipt generation for AUTH CHECKOUT channel
